apiVersion: v1
kind: Service
metadata:
  name: identity-app-service
  labels:
    app: identity-app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.identity.port }}
      targetPort: identity-port
      protocol: TCP
      name: identity-port
  selector:
    app: identity-app
