version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: myuser
      POSTGRES_DB: myapp
    networks:
      - private-network
  user-service:
    image: 'user-service'
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8011-8019:8080"
    networks:
      - private-network
    environment:
      JAVA_OPTS: "-Xss256k"
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
      DATASOURCE_USERNAME: myuser
      DATASOURCE_PASSWORD: passwd
networks:
  private-network:
    driver: bridge