version: '3'
services:
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_DATABASE: postgres
    networks:
      - private-network
  user-service:
    image: 'user-service'
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    links:
      - db
    depends_on:
      - db
    ports:
      - "8011-8019:8080"
    networks:
      - private-network
    environment:
      JAVA_OPTS: "-Xss256k"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
networks:
  private-network:
    driver: bridge