version: '3'
services:
  postgres:
    container_name: 'postgres'
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_USERNAME: myuser
      POSTGRESQL_DATABASE: myapp
    networks:
      - private-network
  user-service:
    image: 'user-service'
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8011-8019:8080"
    networks:
      - private-network
    environment:
      JAVA_OPTS: "-Xss256k"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: 123456
networks:
  private-network:
    driver: bridge