{
 "title": "Otus Homework Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "myapp" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "User API Methods (RPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/v1/user\", method=\"GET\"}[1m]))",
     "legendFormat": "getAllUsers"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"GET\"}[1m]))",
     "legendFormat": "getUserByID"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"POST\"}[1m]))",
     "legendFormat": "newUser"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"PUT\"}[1m]))",
     "legendFormat": "modifyUser"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"DELETE\"}[1m]))",
     "legendFormat": "removeUser"
    }
   ]
  },
  {
   "title": "User API Methods (Errors count)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/api/v1/user\", method=\"GET\", status=\"500\"}[1m]))",
     "legendFormat": "getAllUsers"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"GET\", status=\"500\"}[1m]))",
     "legendFormat": "getUserByID"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"POST\", status=\"500\"}[1m]))",
     "legendFormat": "newUser"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"PUT\", status=\"500\"}[1m]))",
     "legendFormat": "modifyUser"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/api/v1/user/{userId}\", method=\"DELETE\", status=\"500\"}[1m]))",
     "legendFormat": "removeUser"
    }
   ]
  },
  {
   "title": "User API Methods (Latency, ms) - quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getAllUsers"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getUserByID"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"POST\"}[1m]))) * 1000",
     "legendFormat": "newUser"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"PUT\"}[1m]))) * 1000",
     "legendFormat": "modifyUser"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"DELETE\"}[1m]))) * 1000",
     "legendFormat": "removeUser"
    }
   ]
  },
  {
   "title": "nginx Ingress (Latency, ms) - quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "nginx Ingress (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"2..\"}[1m]))",
     "legendFormat": "Income rate (status 20x)"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"3..\"}[1m]))",
     "legendFormat": "Income rate (status 30x)"
    }
   ]
  },
  {
   "title": "User API Methods (Latency, ms) - quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getAllUsers"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getUserByID"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"POST\"}[1m]))) * 1000",
     "legendFormat": "newUser"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"PUT\"}[1m]))) * 1000",
     "legendFormat": "modifyUser"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"DELETE\"}[1m]))) * 1000",
     "legendFormat": "removeUser"
    }
   ]
  },
  {
   "title": "nginx Ingress (Latency, ms) - quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "nginx Ingress (Errors counts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "Income (status 40x)"
    },
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "Income (status 50x)"
    }
   ]
  },
  {
   "title": "User API Methods (Latency, ms) - quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getAllUsers"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "getUserByID"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"POST\"}[1m]))) * 1000",
     "legendFormat": "newUser"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"PUT\"}[1m]))) * 1000",
     "legendFormat": "modifyUser"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{userId}\", method=\"DELETE\"}[1m]))) * 1000",
     "legendFormat": "removeUser"
    }
   ]
  },
  {
   "title": "nginx Ingress (Latency, ms) - quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "PostgresQL Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  }
 ]
}