### addUser
POST http://localhost:8012/user/
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "bestjohn@doe.com",
  "phone": "+71002003040"
}

### getById
GET http://localhost:8012/user/9

### getALL
GET http://localhost:8012/user/

### updateUser
PUT http://localhost:8012/user/9
Content-Type: application/json

{
  "firstname": "upd",
  "lastname": "dated",
  "email": "upd@doe.com",
  "phone": "+71112233344"
}

### deleteById
DELETE http://localhost:8012/user/8


