apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  DATASOURCE_PASSWORD: {{ .Values.externalPostgresql.postgresqlPassword }}
  POSTGRES_PASSWORD: {{ .Values.externalPostgresql.postgresqlPassword }}