apiVersion: v1
kind: Service
metadata:
  name: identity-app-service
  labels:
    app: identity-app
spec:
  selector:
    app: identity-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort