apiVersion: v1
kind: Service
metadata:
  name: billing-app-service
  labels:
    app: billing-app
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.billing.port }}
      targetPort: billing-port
      protocol: TCP
      name: billing-port
  selector:
    app: billing-app
