spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true
  endpoints:
    web:
      base-path: /
      path-mapping.health: health
