apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    {{- include "otus-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otus-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        {{- include "otus-k8s.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          env:
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: DATASOURCE_USERNAME
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: DATASOURCE_PASSWORD
          ports:
            - name: web-port
              containerPort: {{ .Values.configmap.SERVER_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: web-port
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: web-port
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config