apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Chart.Name }}-ns
  labels:
    app.kubernetes.io/name: {{ include "otus-k8s.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-port
      protocol: TCP
      name: web-port
  selector:
    app.kubernetes.io/name: {{ include "otus-k8s.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
