apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "otus-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-port
      protocol: TCP
      name: web-port
  selector:
    {{- include "otus-k8s.selectorLabels" . | nindent 4 }}
