apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus
  namespace: otus-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus
  template:
    metadata:
      name: otus
      labels:
        app: otus
    spec:
      containers:
        - image: achernyavskiy0n/otus-k8s
          name: otus
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 50
            periodSeconds: 5
            failureThreshold: 100
          envFrom:
            - configMapRef:
                name: otus-config