# Default values for otus-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: achernyavskiy0n/user-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 9000

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    host: arch.homework
    paths:
      - path: /(.*)
        pathType: Prefix
        service: otus-service
        port: 9000
      - path: /otusapp/achernyavskiy/(.*)
        pathType: Prefix
        service:  otus-service
        port: 9000
      - path: /(/|$)(.*)
        pathType: Prefix
        service: otus-service
        port: 9000

configmap:
  SERVER_PORT: 8000
  APPLICATION_NAME: otus-k8s-homework-application

postgresql:
  image:
    name: bitnami/postgresql
    pullPolicy: IfNotPresent
    port: 5432
  username: postgres
  password: MTIzNDU2Cg==
  database: postgres

migrationService:
  image: achernyavskiy0n/otus-service-db-init
  pullPolicy: IfNotPresent
  port: 5455


