replicaCount: 2
image: achernyavskiy0n/user-service:latest
service:
  type: NodePort
  port: 9000
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    host: arch.homework
    paths:
      - path: /(.*)
        pathType: Prefix
        service: otus-service
        port: 9000
      - path: /otusapp/achernyavskiy/(.*)
        pathType: Prefix
        service:  otus-service
        port: 9000
      - path: /(/|$)(.*)
        pathType: Prefix
        service: otus-service
        port: 9000
configmap:
  SERVER_PORT: 8000
  APPLICATION_NAME: otus-k8s-homework-application
externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: cGFzc3dk
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: 5432
migrationService:
  image: achernyavskiy0n/otus-service-db-init:latest


