# Default values for otus-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: achernyavskiy0n/otus-k8s
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 9000

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    host: arch.homework
    paths:
      - path: /(.*)
        pathType: Prefix
        service: otus-service
        port: 9000
      - path: /otusapp/achernyavskiy/(.*)
        pathType: Prefix
        service:  otus-service
        port: 9000
      - path: /(/|$)(.*)
        pathType: Prefix
        service: otus-service
        port: 9000

configmap:
  SERVER_PORT: 8000
  APPLICATION_NAME: otus-k8s-homework-application

