replicaCount: 1
service:
  type: NodePort
  identity:
    port: 8082
  billing:
    port: 8081
  order:
    port: 8080
  notes:
    port: 8086
ingress:
  hosts:
    paths:
      - path: /api/v1/identity
        service: identity-app-service
        port: 8082
      - path: /api/v1/order
        service: order-app-service
        port: 8080
      - path: /api/v1/billing/account
        service: billing-app-service
        port: 8081
      - path: /api/v1/notifications
        service: notification-app-service
        port: 8086

