apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: gateway-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.gateway.port }}"
        prometheus.io/path: "/prometheus"
    spec:
      containers:
        - name: news-api-gateway
          image: achernyavskiy0n/api-gateway:v2
          imagePullPolicy: Always
          ports:
            - name: gateway-port
              containerPort: {{ .Values.service.gateway.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: gateway-port
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: gateway-port
            initialDelaySeconds: 600
            periodSeconds: 5
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-gateway-config