externalPostgresql:
  postgresqlUsername: postgres
  postgresqlPassword: cG9zdGdyZXM=
  postgresqlDatabase: news_db
  postgresqlHost: "postgres"
  postgresqlPort: 5432

migrationService:
  image: achernyavskiy0n/news-db-init:v2

replicaCount: 1
service:
  type: NodePort
  providermock:
    port: 8089
  consumermock:
    port: 8088
  delivery:
    port: 8081
  storage:
    port: 8082
  operation:
    port: 8083

ingress:
  hosts:
    paths:
      - path: /api/v1/identity
        service: identity-app-service
        port: 8082