apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-delivery-config
data:
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  SERVER_PORT: '{{ .Values.service.delivery.port }}'
