apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    {{- include "otus-k8s.labels" . | nindent 4 }}
spec:
  rules:
    - host: news.msa
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}

  {{- end }}