apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.kafka.externalport }}
      name: external-port
      targetPort: external-port
      protocol: TCP
    - port: {{ .Values.service.kafka.internalport }}
      name: internal-port
      targetPort: internal-port
      protocol: TCP
  selector:
    app: broker-app